const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("643813432772132867")
setInterval(function() {
channel.send(`fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrg fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr fkejr kjwenr lwker h wer wer wer werwrgre hrtkwr jk i need amars aljns with your fuker mother bc she didn't need me can boy frebid with your bithx dad fucking your mam and your dad bc they are biths and fsdfe werrf werre qwf werfqw ltrmhk tr`);
}, 30)
})

client.login(process.env.BOT_TOKEN);